/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import static java.util.Date.parse;
import java.util.Date; 
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Car;
import model.UberFleet;
import java.text.DateFormat; 
import javax.swing.JOptionPane;

/**
 *
 * @author bhawnasingh
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    private UberFleet uberFleet;
    
    public UpdateJPanel(UberFleet uberFleet) {
        initComponents();
        this.hideAllFields();
        this.uberFleet = uberFleet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serialNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        isAvailable = new javax.swing.JCheckBox();
        maintenanceExpiryDate = new javax.swing.JTextField();
        operatingCity = new javax.swing.JTextField();
        seatingCapacity = new javax.swing.JTextField();
        manufacturedYearTxt = new javax.swing.JTextField();
        manufacturerTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        modelNumberTxt = new javax.swing.JTextField();
        saveToFleet = new javax.swing.JButton();
        fetchCar = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Car");

        jLabel2.setText("Serial Number");

        serialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumberActionPerformed(evt);
            }
        });

        jLabel4.setText("Manufacturer");

        jLabel5.setText("Manufactured Year");

        jLabel6.setText("Seating Capacity");

        jLabel7.setText("Operating City");

        jLabel8.setText("Maintenance Expiration Date (mm/dd/yyyy)");

        jLabel9.setText("Is Available");

        isAvailable.setText("Yes");

        maintenanceExpiryDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceExpiryDateActionPerformed(evt);
            }
        });

        manufacturedYearTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturedYearTxtActionPerformed(evt);
            }
        });

        jLabel10.setText("Model Number");

        saveToFleet.setText("Save");
        saveToFleet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveToFleetMouseClicked(evt);
            }
        });
        saveToFleet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToFleetActionPerformed(evt);
            }
        });

        fetchCar.setText("Fetch Car");
        fetchCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fetchCarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manufacturerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(serialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(modelNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6))))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fetchCar)
                    .addComponent(saveToFleet))
                .addGap(287, 287, 287))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(isAvailable)
                        .addComponent(manufacturedYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(operatingCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maintenanceExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(80, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel2, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {maintenanceExpiryDate, manufacturedYearTxt, manufacturerTxt, modelNumberTxt, operatingCity, seatingCapacity});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fetchCar)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(modelNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manufacturerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(saveToFleet)
                .addGap(102, 102, 102))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(180, 180, 180)
                    .addComponent(jLabel4)
                    .addGap(28, 28, 28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(manufacturedYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(seatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(operatingCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(maintenanceExpiryDate)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(isAvailable))
                    .addContainerGap(177, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumberActionPerformed

    private void maintenanceExpiryDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceExpiryDateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_maintenanceExpiryDateActionPerformed

    private void manufacturedYearTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturedYearTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturedYearTxtActionPerformed

    private void saveToFleetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveToFleetMouseClicked
        // TODO add your handling code here:
        if(this.manufacturedYearTxt.getText().equals("")  || this.manufacturerTxt.getText().equals("")
                || this.seatingCapacity.getText().equals("")|| this.modelNumberTxt.getText().equals("") 
                || this.operatingCity.getText().equals("")
                || this.maintenanceExpiryDate.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Missing Field");
             return;
        }
        try {

        boolean available = this.isAvailable.isSelected();
        String manufacturer = this.manufacturerTxt.getText();
        int manufacturedYear = Integer.parseInt(this.manufacturedYearTxt.getText());
        int seats = Integer.parseInt(this.seatingCapacity.getText());
        String serialNumber = this.serialNumber.getText();
        String modelNumber = this.modelNumberTxt.getText();
        String geoLocality = this.operatingCity.getText();
        Date maintenaceExpiry = new SimpleDateFormat("mm/dd/yyyy").parse(this.maintenanceExpiryDate.getText());
        Car c = new Car(available, manufacturer, manufacturedYear, seats, serialNumber,modelNumber, geoLocality,maintenaceExpiry);
        this.uberFleet.updateCar(c, serialNumber);
        JOptionPane.showMessageDialog(this, "Car Updated In Uber Fleet");
         
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Invalid Field");
        }
        
    }//GEN-LAST:event_saveToFleetMouseClicked

    
    void hideAllFields(){
        this.isAvailable.setVisible(false);
        this.jLabel10.setVisible(false);
        this.jLabel4.setVisible(false);
        this.jLabel5.setVisible(false);
        this.jLabel6.setVisible(false);
        this.jLabel7.setVisible(false);
        this.jLabel8.setVisible(false);
        this.jLabel9.setVisible(false);
        this.maintenanceExpiryDate.setVisible(false);
        this.manufacturedYearTxt.setVisible(false);
        this.manufacturerTxt.setVisible(false);
        this.modelNumberTxt.setVisible(false);
        this.operatingCity.setVisible(false);
        this.saveToFleet.setVisible(false);
        this.seatingCapacity.setVisible(false);
        this.repaint();
    }
    
    void showAllFields(){
        this.isAvailable.setVisible(true);
        this.jLabel10.setVisible(true);
        this.jLabel4.setVisible(true);
        this.jLabel5.setVisible(true);
        this.jLabel6.setVisible(true);
        this.jLabel7.setVisible(true);
        this.jLabel8.setVisible(true);
        this.jLabel9.setVisible(true);
        this.maintenanceExpiryDate.setVisible(true);
        this.manufacturedYearTxt.setVisible(true);
        this.manufacturerTxt.setVisible(true);
        this.modelNumberTxt.setVisible(true);
        this.operatingCity.setVisible(true);
        this.saveToFleet.setVisible(true);
        this.seatingCapacity.setVisible(true);
        this.repaint();
    }
    
    private void fetchCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fetchCarMouseClicked
        // TODO add your handling code here:
        Car c = this.uberFleet.getCarBySerialNumber(this.serialNumber.getText());
        if(c != null){
            DateFormat dateFormat = new SimpleDateFormat("mm/dd/yyyy");  
            this.maintenanceExpiryDate.setText(dateFormat.format(c.getMaintenaceExpiry()));
            this.manufacturedYearTxt.setText(String.valueOf(c.getManufacturedYear()));
            this.manufacturerTxt.setText(c.getManufacturer());
            this.modelNumberTxt.setText(c.getModelNumber());
            this.operatingCity.setText(c.getGeoLocality());
            this.seatingCapacity.setText(String.valueOf(c.getSeats()));
            this.isAvailable.setSelected(c.isAvailable());
            this.showAllFields();
        }else{
            this.hideAllFields();
            JOptionPane.showMessageDialog(this, "No Car for Searched Serial Number");
        }
    }//GEN-LAST:event_fetchCarMouseClicked

    private void saveToFleetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToFleetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveToFleetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fetchCar;
    private javax.swing.JCheckBox isAvailable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maintenanceExpiryDate;
    private javax.swing.JTextField manufacturedYearTxt;
    private javax.swing.JTextField manufacturerTxt;
    private javax.swing.JTextField modelNumberTxt;
    private javax.swing.JTextField operatingCity;
    private javax.swing.JButton saveToFleet;
    private javax.swing.JTextField seatingCapacity;
    private javax.swing.JTextField serialNumber;
    // End of variables declaration//GEN-END:variables
}
